### ISSUE TITLE
duplicated events in summary

### ISSUE THREAD

**Issue by jpata** [grid-control/grid-control#10]
I submit a workflow over 2 datasets:

~~~
datasets/VHBBHeppyV21_tthbbV7_Apr26/ttHTobb_M125_13TeV_powheg_pythia8.txt: Running over 283903 events distributed over 1 blocks.
datasets/VHBBHeppyV21_tthbbV7_Apr26/TT_TuneCUETP8M1_13TeV-powheg-pythia8.txt: Running over 3675580 events distributed over 1 blocks.
Summary: Running over 3959483 events distributed over 2 blocks.
Dataset source will be queried every 4h 00min 00sec
Current task ID: GCa09b354ce138
Task started on 2016-04-27
Using batch system: SLURM (LOCAL)

<SNIP>
Summary: Running over 7918966 events distributed over 4 blocks.
~~~
but somehow the summary reports 2x the events that there should be ( see last line).

**Comment by FredStober** [comment]
Hi, this was just a small issue with the StatsDataProcessor that displays the information. I've added a reset of the counter in ca156d0b05adb790c2c3d7b8fa731eda151157d3 so the displayed numbers are correct when multiple `getBlocks` calls are made. Since the `UniqueDataProcessor` is active and set to `abort` by default, gc will abort if duplicated files are found.
