### ISSUE TITLE
-qs mode

### ISSUE THREAD

**Issue by jpata** [grid-control/grid-control#12]
Hi,

If I create my work area in `-qs` mode to avoid immediate submission, there is a problem:

~~~
$ ./grid-control/go.py confs/tth.conf -qs
Revision: 1704 or later
Starting initialization of work.tth!
Do you want to create the working directory work.tth? [YES/no]:

Exception occured in grid-control [1704]

PluginError: Error while creating instance: 'grid_control.workflow.Workflow'
  PluginError: Error while creating instance: 'grid_control.tasks.task_user.UserTask'
    ConfigError: Unable to parse paths: [usertask] input files = env.sh common.sh
      ConfigError: Error resolving paths
        ConfigError: Could not find file "env.sh" in
        /home/joosep/tth/sw2/CMSSW/src/TTH/MEAnalysis/gc
        /home/joosep/tth/sw2/CMSSW/src/TTH/MEAnalysis/gc/confs
~~~

It used to work in old grid-control, is it still expected to or is there a new way to achieve creation without submission?

**Comment by FredStober** [comment]
Hi,

first, you can drop the '-q' since it is performing a requery of data sources - so it doesn't do anything during workdir initialization. The '-s' alone should already do what you want.

However your problem isn't related to whether or not submission is enabled. The problem is that the file 'env.sh' is not found. Can you check that the file is in one of the two directories listed (and readable)?

**Comment by FredStober** [comment]
PS: If you switch to the stable release r1764, you will get a more detailed error message about the file...

**Comment by jpata** [comment]
Sorry, the `env.sh` was a different issue indeed (my unreliable memory). I did see an error with my usual way of creating the job in the old gc with `-qs` which involved the sandbox being moved but I can't reproduce it at this moment. I'll also update the version, thanks.
